enum InfoEnum
{
    Firmware_Version,
    Hardware_Version,
    System_Running_Time,
    LAN_IP_Address,
    LAN_MAC_Address,
    Line_Download_Speed,
    Line_Upload_Speed,
    Line_State,
    DNS_Servers,
    Connection_Type,
    Internet_State,
    WAN_IP,
    Default_Gateway,
    MAC_Address,
}
enum WifiEnum
{
    WIFI_Name,
    WIFI_Enabled,
    AP_Isolation_Enabled,
    Max_Association,
    Wireless_Media_Extensions_WME_Disabled,
    Wireless_Multicast_Forwarding_WMF_Enabled,
    Mesh_Basic_Service_Set_MBSS_Supported,
    Line_State,
    DNS_Servers
}
enum WifiSecEnum
{
    WIFI_Password,
    WIFI_Authentication,
    WPA_Encryption,
    WEP_Enabled,
    WPS_Enabled,
    RADIUS_IP,
    RADIUS_Port,
    WLCoreRev,
    WPA_Rekey,
    MAC_Filter_Mode,
}
